version: "3.8"
services:
  postgres:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=deposit_app
  elastic:
    image: elasticsearch:7.17.17
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
