app:
  jwt:
    secret: 1234567890abcdeghahjkqwertyasdgh
    expiration-time: 300000
  deposit-limit-percent: 207
spring:
  elasticsearch:
    uris: http://localhost:9200
  jpa:
    open-in-view: false
    properties:
      hibernate:
        show_sql: true
  liquibase:
    change-log: classpath:db.changelog/db.changelog-master.xml
  datasource:
    username: postgres
    password: password
    url: jdbc:postgresql://localhost/deposit_app
logging:
  level:
    ru.alexefremov.depositapp.depositservice: DEBUG
    org.elasticsearch.client.RestClient: ERROR
